### ISSUE TITLE
Undefined method `single_row_mode=' 

### ISSUE THREAD

**Issue by bilby91** [jeremyevans/sequel_pg#25]
Hello,

I'm trying to fix a bug we randomly have in one of our applications. Our initialization code looks very similar to this.

```ruby
DB = Sequel.connect(db_config)

if Sequel::Postgres.supports_streaming?
  DB.extension(:pg_streaming)
  DB.stream_all_queries = true
else
  puts "Streaming not supported" 
end

Sequel.extension :migration

unless Sequel::Migrator.is_current?(DB, File.join(APP_ROOT,"db","migrate"))
  puts "DB is missing migrations"
end
```

We are running `sequel 4.29.0` and `sequel_pg 1.6.13`. 

This is the complete stacktrace (only at the sequel level). 

```
NoMethodError: undefined method `single_row_mode=' for #<Sequel::Postgres::Adapter:0x9c58b50>
/my-app/gems/sequel_pg-1.6.13/lib/sequel/extensions/pg_streaming.rb:45:in `_execute'
/my-app/gems/sequel-4.29.0/lib/sequel/adapters/postgres.rb:340:in `block (2 levels) in execute'
/my-app/gems/sequel-4.29.0/lib/sequel/adapters/postgres.rb:545:in `check_database_errors'
/my-app/gems/sequel-4.29.0/lib/sequel/adapters/postgres.rb:340:in `block in execute'
/my-app/gems/sequel-4.29.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
/my-app/gems/sequel-4.29.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/my-app/gems/sequel-4.29.0/lib/sequel/database/connecting.rb:249:in `synchronize'
/my-app/gems/sequel-4.29.0/lib/sequel/adapters/postgres.rb:340:in `execute'
/my-app/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:950:in `execute'
/my-app/gems/sequel_pg-1.6.13/lib/sequel/extensions/pg_streaming.rb:98:in `fetch_rows'
/my-app/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:833:in `with_sql_each'
/my-app/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:841:in `with_sql_first'
/my-app/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:659:in `single_record!'
/my-app/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:647:in `single_record'
/my-app/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:669:in `single_value'
/my-app/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:247:in `get'
/my-app/gems/sequel-4.29.0/lib/sequel/extensions/migration.rb:542:in `current_migration_version'
/my-app/gems/sequel-4.29.0/lib/sequel/extensions/migration.rb:519:in `is_current?'
/my-app/gems/sequel-4.29.0/lib/sequel/extensions/migration.rb:374:in `is_current?'
```

I read some of the `sequel_pg` code and found that when adding the pg_streaming extension, the extension disconnects the database. I'm thinking that for some reason (under certain conditions) the connection is not back in time and that is why the `single_row_mode` call on the connection fails.

I'm also wondering if this could be related to this fix https://github.com/jeremyevans/sequel_pg/commit/8274ba652b9500d8d15586940af76814169fb598. I'm not familiar with the codebase so all this are wild guesses. 

Thanks before hand!

**Comment by jeremyevans** [comment]
What version of ruby-pg are you using, and what version of PostgreSQL was it compiled with?  Can you reproduce with the current versions of sequel and sequel_pg?

The extension must disconnect the database when loaded, as existing connections won't have the necessary adapter methods added, so that is expected.  I could see there being a problem in threaded cases if a connection was in active use when the extension was loaded, but that seems unlikely in the example code you provided.

**Comment by bilby91** [comment]
@jeremyevans Thanks for the quick reply!

pg version: 9.4.15
ruby-pg (pg gem): 0.18.4

I haven't tried bumping sequel_pg or sequel version yet. I'll try it soon.

So, based on your comment, the reconnection should be done automatically right ? You don't think that https://github.com/jeremyevans/sequel_pg/commit/8274ba652b9500d8d15586940af76814169fb598 could be related then ?

Thanks!

**Comment by jeremyevans** [comment]
Your ruby-pg and PostgreSQL versions look high enough to support single row mode.

I don't think 8274ba652b9500d8d15586940af76814169fb598 is related, because you are getting a NoMethodError.  What appears to be happening is there is a connection left in the connection pool, which doesn't have the AdapterMethods added to it.  The Database's connection pool should disconnect all connections when the sequel_pg extension is loaded into it, so I'm not sure why this would be happening.

Please do test with the current sequel and sequel_pg versions.  If you can recreate the issue with the current versions, please submit a minimal self contained example and I'll see if I can fix it.

**Comment by jeremyevans** [comment]
It's been 5 days without a response.  I'm going to close this now.  If you can post a minimal self contained example showing a bug, I'll definitely review it and reopen this if necessary.

**Comment by bilby91** [comment]
@jeremyevans Totally forgot to reply back. 

At the end it seems to be a concurrency issue. When one task of our tasks was running concurrently with the same task, this problem showed up.

In our case, this concurrent run of task was a mistake, so, fixing that seems to solve the issue.

Thanks for the support as usual!
