### ISSUE TITLE
new versions require pg_inet semantics globally

### ISSUE THREAD

**Issue by fdr** [jeremyevans/sequel_pg#30]
I was testing upgrading gems and narrowed down that sequel_pg upgrades break my application, as they opt me into the IPAddr type for Ruby, something I did not have set before.

The Ruby IPAddr type is cumbersome as comes to CIDR expressions: it make rendering them in the usual, uh, CIDR notation rather difficult, and packages that are far more useful like `NetAddr` don't take them apart very well.

Not sure what the right resolution is. Surely I can make this work, but it may not have been anticipated.

**Comment by jeremyevans** [comment]
This is currently expected as IPAddr is used to implement the native inet/cidr parsers (which can be over 10x faster than the ruby parsers).

If sequel_pg didn't require ipaddr, ruby-pg 1.1.0+ requires it, and since sequel_pg depends on pg, it would be loaded anyway.

If the issue is that IPAddr is now used for inet/cidr and is not possible to override the behavior with conversion procs, I could potentially consider opting out of handling specific types if it has a zero cost if not used and the patch is not invasive. That is probably possible via a compile-time flag when installing the gem and some use of `#ifndef`.  I'm not sure if it is possible to support a runtime setting in a way that is zero cost if not used and not invasive, but I'm open to the possibility.  If you would like sequel_pg to support such a compile time or run time way to opt out, please submit a pull request.

**Comment by fdr** [comment]
I'll look into using conversion procs. On inspection, that looks very reasonable.

**Comment by fdr** [comment]
Oh, I see, a known issue is one cannot override conversion procs for defined type. (I gave it a try and that "known issue" from that readme seems to be up to date). I have relatively few CIDR uses in my application, so it's practical for me to selectively apply some obscura to convert from IPAddr to bona-fide CIDR expressions.

One of the more worrisome aspects of IPAddr with masks is that its to_s ignores the mask outright, returning only the base address. I hope nothing assumes that CIDRs going in would result in bona-fide CIDRs coming out.
